apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tech-challenge-api
  labels:
    app: fiap-tech-challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-tech-challenge-api
  template:
    metadata:
      labels:
        app: fiap-tech-challenge-api
    spec:
      containers:
        - name: fiap-tech-challenge-api-container
          image: $(IMAGE)
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: $(ASPNETCORE_ENVIRONMENT)
            - name: DbConnection__Host
              value: $(DB_HOST)
            - name: DbConnection__Database
              value: $(DB_NAME)
            - name: DbConnection__User
              value: $(DB_USERNAME)
            - name: DbConnection__Password
              value: $(DB_PASSWORD)
            - name: PaymentService__UserId
              value: $(PAYMENT_SERVICE_USER_ID)
            - name: PaymentService__NotificationPaymentUrl
              value: $(PAYMENT_SERVICE_NOTIFICATION_PAYMENT_URL)
            - name: PaymentService__ExternalPosId
              value: $(PAYMENT_SERVICE_EXTERNAL_POS_ID)
            - name: PaymentService__Token
              value: $(PAYMENT_SERVICE_TOKEN)
            - name: PaymentService__BaseUrl
              value: $(PAYMENT_SERVICE_BASE_URL)
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/hc
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/hc
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always