apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tech-challenge-api
  labels:
    app: fiap-tech-challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-tech-challenge-api
  template:
    metadata:
      labels:
        app: fiap-tech-challenge-api
    spec:
      containers:
        - name: fiap-tech-challenge-api-container
          image: fiap-tech-challenge-soat10-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/hc
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/hc
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always