apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: fiap-tech-challenge
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  DbConnection__Host: "postgres"
  DbConnection__Database: "fiap_db"