version: '3.9'

services:
  db:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:      
      POSTGRES_DB: ${DbConnection__Database}
      POSTGRES_USER: ${DbConnection__User}
      POSTGRES_PASSWORD: ${DbConnection__Password}
    volumes:
    - ./database/01-criacao_banco_dados.sql:/docker-entrypoint-initdb.d/01-criacao_banco_dados.sql
    - ./database/02-insert_dados_iniciais.sql:/docker-entrypoint-initdb.d/02-insert_dados_iniciais.sql
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
