version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnection__Host=db
      - DbConnection__Database=${DbConnection__Database}
      - DbConnection__User=${DbConnection__User}
      - DbConnection__Password=${DbConnection__Password}
    networks:
      - app-network

  db:
    image: postgres:17.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DbConnection__User} -d ${DbConnection__Database}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    ports:
      - "5432:5432"
    environment:      
      POSTGRES_DB: ${DbConnection__Database}
      POSTGRES_USER: ${DbConnection__User}
      POSTGRES_PASSWORD: ${DbConnection__Password}
    volumes:
      - ./database/01-criacao_banco_dados.sql:/docker-entrypoint-initdb.d/01-criacao_banco_dados.sql
      - ./database/02-insert_dados_iniciais.sql:/docker-entrypoint-initdb.d/02-insert_dados_iniciais.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata: