apiVersion: v1
kind: Service
metadata:
  name: fiap-tech-challenge-mock-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30004
      protocol: TCP
  selector:
    app: fiap-tech-challenge-mock