apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secrets
          resources:
            limits:
              cpu: "0.3"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /api/hc
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/hc
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always