apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  DbConnection__Host: "${DB_HOST}"
  DbConnection__Database: "${DB_NAME}"
  DbConnection__User: "${DB_USERNAME}"
  DbConnection__Password: "${DB_PASSWORD}"
  PaymentService__Token: "${PAYMENT_SERVICE_TOKEN}"      