@startuml
!include <C4/C4_Container>

System_Boundary(c1, "Sistema de Autoatendimento") {
    Container(apiPedidos, "API Order", "C# .NET, Entity Framework", "Gerencia pedidos")
    Container(apiAutenticacao, "API Identity", "C# .NET, Entity Framework", "Gerencia autenticação")
    Container(apiCarrinho, "API Cart", "C# .NET, Entity Framework", "Gerencia carrinho de compras")
    Container(apiPagamento, "API Payment", "C# .NET, Entity Framework, Refit", "Gerencia pagamentos")
    Container(webhookPagamento, "Webhook Payment Notifications", "C# .NET, Entity Framework", "Recebe notificações de pagamento")    
}

System_Boundary(aws, "AWS") {
    ContainerDb(database, "AWS RDS", "PostgreSQL", "Armazena dados da aplicação")
}

System_Ext(paymentService, "Mercado Pago", "Processa pagamentos")

Rel(apiPedidos, database, "Armazena e consulta dados", "ORM EF Core")
Rel(apiAutenticacao, database, "Consulta dados", "ORM EF Core")
Rel(apiCarrinho, database, "Armazena e consulta dados", "ORM EF Core")
Rel(apiPagamento, database, "Armazena e consulta dados", "ORM EF Core")
Rel(apiPagamento, paymentService, "Integra com", "HTTP")
Rel(paymentService, webhookPagamento, "Envia notificações", "HTTP")
Rel(webhookPagamento, database, "Atualiza dados", "ORM EF Core")

@enduml