name: Deploy dos pacotes das aplicações
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
          required: true
          type: string
      image: 
          required: true
          type: string
env:
  EKS_NAME: "${{ inputs.environment }}-${{ vars.BASE_EKS_CLUSTER_NAME }}"
  ASPNETCORE_ENVIRONMENT: ${{ inputs.environment == 'dev' && 'Development' || 'Production' }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  PAYMENT_SERVICE_USER_ID: ${{ vars.PAYMENT_SERVICE_USER_ID }}
  PAYMENT_SERVICE_NOTIFICATION_PAYMENT_URL: ${{ vars.PAYMENT_SERVICE_NOTIFICATION_PAYMENT_URL }}
  PAYMENT_SERVICE_EXTERNAL_POS_ID: ${{ vars.PAYMENT_SERVICE_EXTERNAL_POS_ID }}
  PAYMENT_SERVICE_TOKEN: ${{ secrets.PAYMENT_SERVICE_TOKEN }}
  PAYMENT_SERVICE_BASE_URL: ${{ vars.PAYMENT_SERVICE_BASE_URL }}
jobs:

  deploy:
    name: "Deploy da aplicação ${{ inputs.app_name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_NAME
      
      - uses: azure/setup-kubectl@v4
        id: install-kubectl

      - name: Deploy to EKS
        run: |
          kubectl apply -f ${{ inputs.app_name }}-deployment.yaml
          kubectl apply -f ${{ inputs.app_name }}-service.yaml
          kubectl apply -f ${{ inputs.app_name }}-hpa.yaml