name: Build dos pacotes das aplicações
on:
    push:
      branches: [ develop, 'feature/publicacao_kubernetes' ]   # Aceita push em qualquer branch
    pull_request:

jobs:
  build_api:      
      uses: ./.github/workflows/build.yaml
      secrets: inherit
      with:
        app_name: api
        app_project_name: src/Soat10.TechChallenge.API  