name: Build dos pacotes das aplicações
on:
    push:
      branches: [ develop ]   # Aceita push em qualquer branch
    pull_request:
env:
  ENVIRONMENT: ${{ (github.ref_name == 'main' || github.event_name == 'pull_request') && 'prod' || 'dev' }}
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.ENVIRONMENT }}
    steps:
      - name: Set outputs
        run: echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
  build_api:      
      uses: ./.github/workflows/build.yaml
      secrets: inherit
      with:
        app_name: api
        app_docker_image: DockerfileApi
        ecr_repository: ${{ vars.API_ECR_REPOSITORY }}
  
  deploy_api:
      needs: [setup, build_api]
      uses: ./.github/workflows/deploy.yaml
      secrets: inherit
      with:
        app_name: api
        environment: ${{ needs.setup.outputs.environment }} 
        image: ${{ needs.build_api.outputs.image }}

  build_webhook:      
      uses: ./.github/workflows/build.yaml
      secrets: inherit
      with:
        app_name: webhook
        app_docker_image: DockerfileWebhook
        ecr_repository: ${{ vars.WEBHOOK_ECR_REPOSITORY }}

  deploy_webhook:
    needs: [setup, build_webhook]     
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      app_name: webhook
      environment: ${{ needs.setup.outputs.environment }} 
      image: ${{ needs.build_webhook.outputs.image }}
  
  output:
      needs: [deploy_api, deploy_webhook]
      runs-on: ubuntu-latest
      steps:
        - name: Get shared ALB address
          run: |
            echo "Waiting for ALB address..."
            
            ATTEMPTS=0
            MAX_ATTEMPTS=60
            
            while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
              ALB_ADDRESS=$(kubectl get ingress api-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
              
              if [ -n "$ALB_ADDRESS" ]; then
                echo "SHARED_ALB_ADDRESS=$ALB_ADDRESS" >> $GITHUB_ENV
                echo "Shared ALB deployed at: $ALB_ADDRESS"
                break
              fi
              
              ATTEMPTS=$((ATTEMPTS+1))
              echo "Attempt $ATTEMPTS/$MAX_ATTEMPTS - waiting 10 seconds..."
              sleep 10
            done
