name: Build dos pacotes das aplicações
on:
    push:
      branches: [ develop, 'feature/publicacao_kubernetes' ]   # Aceita push em qualquer branch
    pull_request:

jobs:
  build_api:      
      uses: ./.github/workflows/build.yaml
      secrets: inherit
      with:
        app_name: api
        app_project_path: src/Soat10.TechChallenge.API
  
  deploy_api:
      needs: build_api
      uses: ./.github/workflows/deploy.yaml
      secrets: inherit
      with:
        app_name: api

  build_webhook:      
      uses: ./.github/workflows/build.yaml
      secrets: inherit
      with:
        app_name: webhook
        app_project_path: src/Soat10.TechChallenge.Webhook

  deploy_webhook:
    needs: build_webhook          
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      app_name: webhook