name: Deploy dos pacotes das aplicações
on:
  workflow_call:
    inputs:
      environment:
          required: true
          type: string
env:
  EKS_NAME: "${{ inputs.environment }}-${{ vars.BASE_EKS_CLUSTER_NAME }}"  
jobs:

  output:
    name: "Display output resources"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.EKS_NAME }}
      
      - uses: azure/setup-kubectl@v4
        id: install-kubectl
      
      - name: Get shared ALB address
        run: |
          echo "Waiting for ALB address..."
          
          ATTEMPTS=0
          MAX_ATTEMPTS=60
          
          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            ALB_ADDRESS=$(kubectl get ingress api-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            
            if [ -n "$ALB_ADDRESS" ]; then
              echo "SHARED_ALB_ADDRESS=$ALB_ADDRESS" >> $GITHUB_ENV
              echo "Shared ALB deployed at: $ALB_ADDRESS"
              break
            fi
            
            ATTEMPTS=$((ATTEMPTS+1))
            echo "Attempt $ATTEMPTS/$MAX_ATTEMPTS - waiting 10 seconds..."
            sleep 10
          done
  
      