name: Configure prerequisites to deploy
on:
  workflow_call:
    inputs:      
      environment:
          required: true
          type: string
env:
  EKS_NAME: "${{ inputs.environment }}-${{ vars.BASE_EKS_CLUSTER_NAME }}"  
jobs:

  setup:
    name: "Configure prerequisites to deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.EKS_NAME }}
      
      - uses: azure/setup-kubectl@v4
        id: install-kubectl
      
      - uses: azure/setup-helm@v4.3.0
        id: install-helm
      
      - name: Configure Load Balancer
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update eks
          helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=${{ env.EKS_NAME }} \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller \
            --version 1.13.0
      
      - name: Confiure metrics service
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml